version: "3.8"

services:
  db:
    container_name: gis_db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webgis-network

  backend:
    build: ./backend
    container_name: gis_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - webgis-network

  frontend:
    image: nginx:alpine
    container_name: gis_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webgis-network

networks:
  webgis-network:

volumes:
  db_data:
